- name: Installation de la clef SSH
  connection: local
  hosts: localhost
  roles:
  - ssh_keygen

- name: Installation de Nginx 
  hosts: nginx
  become: yes
  roles:
  - nginx

- name: Installation de php_fpm 
  hosts: php_fpm
  become: yes
  roles:
    - php-fpm

